### ISSUE TITLE
Where is the Range<> template?

### ISSUE THREAD

**Issue by ivorjawa** [tomstewart89/BasicLinearAlgebra#1]
README.md:auto ref = A.Submatrix(Slice<1,3>(),Range<0,2>()));

**Comment by tomstewart89** [comment]
Thanks for the comment! I actually renamed "Range" to "Slice" a while ago to better conform with the terminology used in numpy; so just use Slice instead. Looks like I missed a spot when I was updating the readme though so I'll fix that up
