### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by Cabzx** [tomstewart89/BasicLinearAlgebra#10]
Hello,

I am trying to run the examples as provided but I am getting some errors. My Arduino IDE version is 1.0.5-r2

In "HowToUse.ino" I get the following error on line 35:

<pre>
&nbsp;&nbsp;<span style="color: #CC6600;">Matrix</span>&lt;3,3&gt; B = {6.54, 3.66, 2.95,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.22,&nbsp;7.54,&nbsp;5.12,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8.98,&nbsp;9.99,&nbsp;1.56};

</pre>

Error message at compilation is

`HowToUse.ino: In function 'void setup()':
HowToUse:35: error: braces around initializer for non-aggregate type 'Matrix<3, 3, Array<3, 3, float> >'`

**Comment by Cabzx** [comment]
I'll add that there are no errors on 1.8.3.

**Comment by tomstewart89** [comment]
Yeah this library uses a bunch of C++11 features which aren't enabled by default in Arduino IDE 1.0.5. You can enable them manually, but the easiest thing to do would just be to use the later version of the IDE
