### ISSUE TITLE
What data type to return in function?

### ISSUE THREAD

**Issue by stationaryfront** [tomstewart89/BasicLinearAlgebra#12]
Hello,

I'm writing a class with `Matrix` class as constructor parameters.
Some of functions of this class also return `Matrix`.
I tried `Matrix<int, int>` and `Matrix<int, int, class, class>` as data type to return in my function but both of them didn't work.

Here's the error message:
`error: type/value mismatch at argument 1 in template parameter list for 'template<int rows, int cols, class ElemT, class MemT> class Matrix'
   Matrix<int, int, class, class> _R;`

**Comment by tomstewart89** [comment]
So the problem is that it's not possible to pass template parameters in that way. If   So the issue here is that Matrix is a template class so its template parameters (rows, cols etc) have to be set at compile time. If you want to use Matrix as a member of a class you'll have to either
