### ISSUE TITLE
Transpose function

### ISSUE THREAD

**Issue by juanjqo** [tomstewart89/BasicLinearAlgebra#14]
Dear Tom, 

I do not find the transpose function. 
Can you include it in the library?

Thanks, 

Juan

**Comment by tomstewart89** [comment]
Hey Juan,
The transpose function is handled by the operator ~. So to take the transpose of a matrix you'd write: 
```
Matrix<4,2> A;
Matrix<2,4> B;
A = ~B;
```

**Comment by juanjqo** [comment]
Great!
Thank you Tom!
