### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by VorpalBlade** [tomstewart89/BasicLinearAlgebra#23]
I noticed that there is no license specified, which to my knowledge means that it actually isn't open source currently, nor am I allowed to redistribute code using this library. It would be very useful if you could specify the license, I assume it is just a mistake that it is missing.

https://choosealicense.com/no-permission/ might be a useful resource for you in case you are not well versed in why this is a problem. That site also provides some advice for finding a suitable license.

**Comment by tomstewart89** [comment]
Ah well spotted, you're right it wasn't omitted on purpose. I've added an MIT license now so feel free to use the library however you like, enjoy!
