### ISSUE TITLE
Something weird is happening when I want to display the Matrix data

### ISSUE THREAD

**Issue by ripponds** [tomstewart89/BasicLinearAlgebra#28]
Hi Tom, 

I want to send data via serial communication, as you can see in the picture. If I write a random float numbers instead "PV(1,1)" and "PV(2,1)" the numbers are displayed in Simulink without problem. So, sending data it's not the problem.

I was testing how to send matrix values created with your library. The strange thing happened when I wanted to send "PV(1,1)" and "PV(2,1)", It was declared like this "BLA::Matrix<2,1> PV;" then in the loop, I filled the matrix "PV" as shown in the picture. The code compiled without errors so , when I went To simulink, It displayed the values of "SEPO"... I tested with "Monitor Serie" in Arduino and the same problem. 

I also tested sending "SEPO" values and Simulink displayed "nan, nan" 

Finally I created a new matrix "e" and I assigned values after "PV"  as shown in the second picture. Simulink displayed now "PV" values... 

IDK what's wrong, its my first time using your powerfull library, but I don't know if I skipped a step or what happen :(

Kind regards from Colombia :D

![GitHub](https://user-images.githubusercontent.com/71950128/97135254-c87c1e80-171d-11eb-9bb4-c1891fc329ae.png)
![GitHub2](https://user-images.githubusercontent.com/71950128/97138626-a2a74780-1726-11eb-953b-e4764ba910be.png)

**Comment by tomstewart89** [comment]
Hey @ripponds , sorry it took me a while to get back to you here. I'm not really sure what the problem might be but do you think you could share a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) that I can run and see `nan` values being printed to the arduino serial monitor?

**Comment by tomstewart89** [comment]
I'm going to close this guy since it's been inactive for a while now. @ripponds if you're still having trouble feel free to re-open!
