### ISSUE TITLE
Suggestion: Overload for floats

### ISSUE THREAD

**Issue by DaniloZZZ** [tomstewart89/BasicLinearAlgebra#3]
It would be very helpful if I could multiplicate every element by a float using just `matrix *= float.` Also `matrix2 = matrix1+float` would be useful to add float to each element.

**Comment by tomstewart89** [comment]
Sounds good! I'll have a run at it over the weekend

**Comment by DaniloZZZ** [comment]
Thanks a lot! Your lib is very useful

**Comment by tomstewart89** [comment]
Thanks! I'm pleased to see it being put to use. Those overloads should be in there now so let me know if there's anything I missed. In the meantime, I'll have a look at that assignment feature
