### ISSUE TITLE
Matrix Multiplication with different sized matrices gives errors

### ISSUE THREAD

**Issue by rbbrown1** [tomstewart89/BasicLinearAlgebra#35]
When I try to multiply matrices of different sizes (while ensuring the dimensions are compatible), the compiler says there are dimension issues. The following code will consistently give me the error when attempting to do C = A*B:
`#include` <BasicLinearAlgebra.h>

using namespace BLA;

void setup() {
  Matrix<2,2> A;
  A.Fill(1);

  Matrix<2,1> B;
  B.Fill(2);

  Matrix<2,1> C = A * B;
}

void loop() {}`

**Comment by tomstewart89** [comment]
Hi @rbbrown1, that's a strange one, I just copied that code you linked and and was able to compile it just fine. Can you post the full compiler output?

**Comment by rbbrown1** [comment]
Hi @tomstewart89, In my process of debugging, I downgraded the library to version 2.2 and the example code worked. When I moved back to version 2.3, the error was no more. 

I appreciate your prompt reply, but It appears the issue has somehow resolved itself. If the problem reappears, I'll be sure to better document the output and give an update.
