### ISSUE TITLE
Initialize Matrix to 0

### ISSUE THREAD

**Issue by PJansky** [tomstewart89/BasicLinearAlgebra#45]
I would expect you could initialize a Matrix with zeros like this;
`BLA::Matrix<3, 3> A = {0};`
Unfortunatly this doesn't seem to be the case. All subsequent values stay uninitialized . I'm aware the "HowToUse" doesn't explicitly say this should possible, but since you can do this
`BLA::Matrix<3, 3> B = {6.54, 3.66, 2.95, 3.22, 7.54, 5.12, 8.98, 9.99, 1.56};`
I thought the afor mentioned way would also work. 

Otherwise the Library works as advertised :) Keep up the good work!

**Comment by tomstewart89** [comment]
Hey @PJansky thanks for the info, glad you're getting some use out of this library!

Yeah I guess that behavior is a bit unexpected. I guess I can add some code such that when an intiialiser list is passed that shorter than the length of the matrix, then consider the trailing elements as zero. This seems to be the rule with regular C-arrays (for example: https://godbolt.org/z/jKq84f5P7) so it makes sense to follow that convention here too.

In the meantime, you can zero-initialise a matrix using the `Zeros` type like so:

```cpp
BLA::Matrix<3, 3> A = BLA::Zeros<3,3>;
```
Hope that helps!

**Comment by tomstewart89** [comment]
Ok, this should be fixed in version 3.6
