### ISSUE TITLE
Delete a matrix instace

### ISSUE THREAD

**Issue by VitorCMatias** [tomstewart89/BasicLinearAlgebra#50]
Hello, I am using you pack in a project , and I need to delete some matrix objecs, but I did not fount a proper function in the documentation, does a function like that exists?
I am using the Invert function like this: `inv_a = Invert(A);`

**Comment by tomstewart89** [comment]
Hey @VitorCMatias, assuming you declared your `Matrix` as a local variable (i.e somewhere inside a pair of curly braces  `{}`) then the Matrix will automatically be deleted when it goes out of scope (i.e when execution reaches the closing `}`). So for example:

```cpp
void foo()
{
    BLA::Matrix<3,3> bar;

    // some other stuff
} // bar will be deleted when execution reaches this line
```
From your  code snippet I'm guessing that you'd like to delete that `A` matrix once you've found its inverse. In that case I'd recommend just using the [in-place inversion function](https://github.com/tomstewart89/BasicLinearAlgebra/blob/771229f258c4643152d8cd804f4b35b90467ed8a/impl/NotSoBasicLinearAlgebra.h#L219) which'll save you allocating `inv_a` in the first place.

Hope that helps! Let me know if you have any trouble
