### ISSUE TITLE
Sparse matrix

### ISSUE THREAD

**Issue by lukrow80** [tomstewart89/BasicLinearAlgebra#52]
Hi, the code on read.me do not compile.
Matrix<2000,3000, float, Sparse<3000,100,float> > sparseMatrix; 

I changed to

Matrix<2000,3000, Sparse<3000,100,float> > sparseMatrix; 

Ten i van compile but i cant assign aby value to sparse Matrix? 
Can you give me an example of use sparse matrix? A example on how IT works would be great. Thanx

**Comment by tomstewart89** [comment]
Hey @lukrow80, sorry about the slow response here. I just released a new version of this library in which the sparse matrix class should work ok. I also added some logic to show how to do sparse multiplication ([here](https://github.com/tomstewart89/BasicLinearAlgebra/blob/26d44b16718ee7663e0290fa1ace40ada99636c2/test/test_linear_algebra.cpp#L104)). I'm not really sure how to better support operations on sparse matrices so for now I've just left that code in one of the tests. Hope that's helpful!

**Comment by lukrow80** [comment]
Hey, thanx for your work. I will tast it.Od: tomstewart89 ***@***.***>Wysłano: sobota, 26 listopada 2022, 04:38Do: tomstewart89/BasicLinearAlgebra ***@***.***>DW: lukrow80 ***@***.***>; Mention ***@***.***>Temat: Re: [tomstewart89/BasicLinearAlgebra] Sparse matrix (Issue #52)
Hey @lukrow80, sorry about the slow response here. I just released a new version of this library in which the sparse matrix class should work ok. I also added some logic to show how to do sparse multiplication (here). I'm not really sure how to better support operations on sparse matrices so for now I've just left that code in one of the tests. Hope that's helpful!
