### ISSUE TITLE
A 3D pose representation to work with the basicLinearAlgebra library

### ISSUE THREAD

**Issue by Akshay5312** [tomstewart89/BasicLinearAlgebra#53]
I use this library to work with robots, and had to develop an extension to work with 3D poses. 
An implementation of 3D pose representations that work with BasicLinearAlgebra matrices/vectors would be helpful!

**Comment by tomstewart89** [comment]
Hey @Akshay5312, I'm glad you're getting some use out of my library!

I have another library ([here](https://github.com/tomstewart89/Geometry)) built on top of this one for managing poses and twists and so on, would that work for you're use case?

**Comment by Akshay5312** [comment]
It does, and goes beyond! Does the geometry library have methods to compute linked frame jacobians?

**Comment by tomstewart89** [comment]
> It does, and goes beyond! Does the geometry library have methods to compute linked frame jacobians?

It doesn't, but it probably wouldn't be difficult to add that functionality. If you want to have a run at it and make a PR then I'd be happy to review it!
