### ISSUE TITLE
Multiplying a Matrix times a scalar

### ISSUE THREAD

**Issue by keithmgould** [tomstewart89/BasicLinearAlgebra#9]
Motivation: In an effort to do `x_hat_new = A*x_hat + B*u`

The `A*x` is easy since both are matrices.

I'd like to do something like:
```
Matrix<3,1> B, foo;
B << 1,2,3;
float u;
u = 0.5;
foo = B * u;
// or even:
ScalarMultiply(B, u, foo);
// where foo is now {{0.5},{1},{1.5}}
```

I suspect this is not possible given BLA's current state. If its possible let me know, otherwise I'd be happy to write a PR.

**Comment by tomstewart89** [comment]
As of fairly recently this is supported along with elementwise addition subtraction and division. You can call them through the operators or use ElementwiseMultiply etc to save a bit of overhead.

Let me know you have problems!

**Comment by keithmgould** [comment]
Ah fantastic. Works great. I got lazy and did not read through source. Looks like it is not in readme (unless I missed it?) Want a PR augmenting?

**Comment by tomstewart89** [comment]
Sure! I'm not one to turn down a good PR!
